name: conformalized-gp
channels:
    - defaults
    - conda-forge
dependencies:
    - bump2version=1.0.1
    - flake8=4.0.1
    - ipykernel=6.9.0
    - jupyter=1.0.0
    - numpy=1.22.3
    - openturns=1.21
    - pandas=1.3.5
    - python=3.10
    - scikit-learn
    - seaborn=0.12.2
    - pip
    - pip:
        - ucimlrepo