name: conformalized-gp
channels:
    - conda-forge
dependencies:
    - bump2version=1.0.1
    - flake8=4.0.1
    - ipykernel=6.9.0
    - jupyter=1.0.0
    - numpy=1.22.3
    - pandas=1.3.5
    - python=3.10
    - scikit-learn
    - seaborn>=0.13
    - pip
    - pip:
        - ucimlrepo
        - openturns==1.23rc1